# Utiliser RStudio sur l'environnement AUSv3 {#AUSv3}

::: recommandation
Vous pouvez utiliser `R` et RStudio sur la collection `R`-Python de l'environnement AUSv3 pour réaliser des tâches de production statistique et des études, et pour traiter des données confidentielles. Si vous souhaitez mener des expérimentations qui requièrent des ressources informatiques importantes ou un accès à internet, il est préférable d'utiliser le SSP Cloud.
:::

## Présentation succincte d'AUSv3

Mis à disposition de logiciels 



## Comment se connecter à AUSv3

### Obtenir un accès à AUSv3

### Ouvrir une session sur AUSv3

::: remarque
Blabla
:::

## Utiliser RStudio dans AUSv3

### Ouvrir RStudio

Pour ouvrir RStudio dans AUS, il suffit de double-cliquer sur l'icône RStudio présente sur le bureau d'AUS.

```{r, echo = FALSE}
utilitr::include_image("./pics/AUSv3/Desktop_AU.png")
```


### Travailler avec Git sur AUSv3

#### Créer une clé SSH/token https


#### Où stocker les dépôts locaux

Lorsque vous créez un projet RStudio en clonant un dépôt distant, il est nécessaire de définir l'emplacement de votre dépôt local. Dans AUSv3, il est conseillé de stocker vos dépôts locaux dans votre espace personnel `U:`. Par exemple, vous pouvez stocker tous vos dépôts dans un dossier `U:/DepotsGit`. En revanche, il est fortement déconseillé de stocker un dépôt local dans un coffre ou dans un espace partagé, car d'autres agents peuvent avoir accès à votre dépôt local.

### Liste des programmes utiles



`Y:/Logiciels` ;

## Pour en savoir plus

- La documentation d'AUSv3 est disponible dans le dossier `Y:/Documentation/AUSv3`.
