## Comment installer un package ?

Un package est une extension des fonctionnalités de base de R. Il est constitué d'objets R (la plupart du temps des fonctions, parfois des données) empaquetés en un seul fichier, dans le but d'être partagé facilement entre utilisateurs.

Les packages sont au coeur de la logique collaborative de `R`. Ils permettent de bénéficier des contributions d'autres utilisateurs de R et de partager avec d'autres des fonctionnalités utiles. Il est donc primordial de savoir où chercher les packages et comment les installer.

### Installer depuis un dépôt de packages distant

La façon la plus commune (et commode) d'installer un package est d'utiliser la fonction `install.packages` dont la syntaxe est la suivante :

```r
install.packages("<nom du package entre guillemets>")
```

Cette fonction réalise successivement deux actions :

1. téléchargement de la dernière version du package sur un dépôt distant de packages R (typiquement le dépôt officiel) ;
2. installation du package sur la machine de l'utilisateur.

Le package est installé **de manière permanente** sur la machine. Cela signifie que la manipulation ci-dessous n'est à réaliser qu'une fois (sauf si on souhaite mettre le package à jour).

::: {.remarque data-latex=""}
Les noms des packages sont sensibles à la casse : bien respecter majuscules et minuscules.
:::

La fonction accepte en paramètre un vecteur de noms de packages, afin d'installer plusieurs packages en une seule instruction :

```r
install.packages(c("package1", "package2", "package3"))
```

Un package repose la plupart du temps sur d'autres packages pour fonctionner. Ces packages sont appelés _dépendances_. Par défaut, `install.packages` installe également toutes les dépendances nécessaires. Ce comportement est modifiable via l'argument `dependencies`.

::: {.remarque data-latex=""}

Si les packages sont _installés_ une fois pour toutes. il reste néanmoins impératif de les _charger_ **à chaque utilisation** avec `library(...)`. Ceci rend ses fonctionnalités disponibles dans la session `R` en cours. Pour éviter des réinstallations superflues, les programmes R ne contiennent en génral pas les instructions d'installation des packages, mais seulement les instructions de chargement en début.

:::

#### Choix du dépôt

Par défaut, `install.packages` télécharge le package sur le dépôt officiel du projet `R`, le [CRAN](https://cran.r-project.org) (Comprehensive R Archive Network).

Le CRAN dispose de plusieurs copies exactes de son contenu. Ces copies, appelées _miroirs_, sont la plupart du temps hébergés sur des [serveurs d'universités ou d'établissements de recherche](https://cran.r-project.org/mirrors.html). Télécharger un package sur un miroir ou un autre est strictement équivalent. L'intérêt de choisir un miroir proche de sa localisation est uniquement de limiter les flux de données sur le réseau.

Pour connaître le dépôt qui sera utilisé par défaut lors d'une installation :
```r
getOption("repos")
```
Il est également possible de spécifier le dépôt grâce à l'argument `repos` de `install.packages`.

::: {.remarque data-latex=""}

À l'Insee, les packages installés sur **AUS** sont récupérés sur un dépôt accessible seulement en interne, https://nexus.insee.fr. Ce dépôt permet de contourner le fait qu'internet ne soit pas accessible depuis AUS. Il est actualisé sur le CRAN quotidiennement.

Ce dépôt diffère des miroirs listés sur le CRAN par les aspects suivants :

- il n'est accessible que depuis le réseau Insee ;
- il peut héberger des packages développés en interne et ajoutés sans passer être soumis au CRAN.

Sur AUS, `R` est configuré de manière à chercher automatiquement les packages sur ce dépôt interne. En local sur un poste Insee, on peut aussi y accèder comme n'importe quel miroir (option ou argument `repos`) :

```r
# spécifier le dépôt Insee à chaque installation
install.packages("package1", repos = "https://nexus.insee.fr/repository/r-public")

# pour conserver le réglage
options(repos = "https://nexus.insee.fr/repository/r-public")
# ce qui permet d'omettre `repos` pour toute la session R
install.packages("package1")
```

:::

### Type de packages

<!-- à compléter -->

### Installer depuis une forge logicielle (GitHub, GitLab...)

<!-- à compléter -->

### Installer depuis un fichier

Il est aussi possible d'installer un package depuis une archive compressée (fichiers ".zip" pour les binaires Windows ou ".tar.gz" pour les packages _source_).

```r
install.packages("chemin/en/local/package1_x.y.z.zip", repos = NULL)
```
Pour indiquer que la source est un fichier local, il est obligatoire de spécifier `repos = NULL`.

Si le fichier est de type "source" (extension .tar.gz), Rtools peut là encore s'avérer nécessaire, notamment si certaines fonctions sont écrites en C ou C++.

Cette solution sera utilisée dans les cas suivants : 

- le package n'est pas sur un dépôt distant (CRAN ou une forge logicielle)
- on souhaite installer une version plus ancienne que celle actuellement sur le dépôt distant
- aucune connexion internet n'est possible (par exemple, transmission du fichier compressé via une clé usb)

Il est à noter que cette méthode atteint rapidement ces limites dès lors que des dépendances pas encore installées sont requises.

### Emplacement des packages installés

Par défaut, les packages sont installés :

- **sur poste** : dans le sous-dossier "library" de l'emplacement où est installé `R` ;
- **sur AUS** : sur son espace personnel, dans le dossier `U:/R/win-library/x-y`, où `x-y` désigne le numéro de version de `R`.

Dans les deux cas, les packages sont associés à une version particulière de `R`. Ainsi, installer un package depuis une version différente de R installera les packages dans un dossier distinct. Dans cette configuration, passer à une nouvelle version de R requerra notamment d'avoir à réinstaller les packages.

Ce classement limite les risques d'incompatibilité entre versions de R et versions des packages. En effet, certains packages ont besoin d'une version minimale de `R` pour fonctionner.

Pour connaître les répertoires où sont recherchés les packages à charger, utiliser l'instruction `.libPaths()`. Il est possible de modifier cet emplacement, voire de définir plusieurs emplacements où les packages seront successivement recherchés lors de l'appel à `library()` (sous réserve d'avoir accès en écriture au dossier).

Changer `libPaths` est cependant une pratique avancée, à déconseiller si on veut s'éviter tout problème de compatibilité entre versions.

### Mettre à jour les packages

<!-- à compléter -->

### Gestion des packages avec RStudio

`RStudio` dispose d'un onglet "Packages" (par défaut dans le cadran en bas à droite) où l'on peut gérer les packages sans saisir des instructions dans la console. Les fonctionnalités principales sont les suivantes :

- affichage des packages installés sur le système (correspond au résultat de la fonction `installed_packages`). Cocher un package dans cette liste le charge en mémoire (`library`).
- bouton "Install" permet de chercher un package sur le CRAN (ou un autre dépôt) ou de sélectionner un package sous forme de fichier. L'auto-complétion sur le nom du package est proposée lors de la recherche, ce qui la rend plus aisée et prévient les problèmes de casse (majuscules / minuscules).
- bouton "Update" permet de lister les packages pour lesquels il existe une version plus récente et d'éventuellement les mettre à jour.

Chacune de ces manipulations effectuées par l'intermédiaire de l'interface graphique génère (et exécute) la commande correspondante dans la console.

Lors de l'ouverture d'un script, `RStudio` tente aussi de détecter automatiquement si les packages utilisés dans celui-ci sont installés. Dans le cas contraire, il affiche un bandeau en haut du script proposant d'installer les packages manquants :
`▲ Package --- required but is not installed. Install Don't show again`

::: {.remarque data-latex=""}
Sur **AUS**, ne pas installer les package à partir de ce bandeau. RStudio essaie en effet de télécharger depuis le CRAN, qui n'est pas accessible depuis AUS).
:::


<!-- 

# Installer des _packages_

L'utilisateur souhaite installer des _packages_. Cette fiche doit aller avec les fiches "Comment gérer ses dépendances", 

## Un plan très rapide

### En vrac, les élements qu'il va falloir définir à un moment
- c'est quoi un _package_?
- distinction source/binary
- c'est quoi un repo? Nexus, Cran, Github/Gitlab.
- c'est quoi Rtools? Comment savoir si `R` sait où trouver Rtools?
- c'est quoi une librairie?
- `.libPaths()`.
- C'est quoi une dépendance de _package_?

### Introduction aux _packages_

#### C'est quoi un _package_?

Traduire des éléments existants en anglais, et donner quelques exemples. Expliquer pourquoi on doit installer des _packages_ et que les _packages_ sont au coeur de la logique collaborative de `R`.

#### Qu'est-ce qu'une dépendance?

Traduire des éléments existants en anglais, et donner quelques exemples.

Remarque: utiliser beaucoup de _packages_ fragilise le code. Il faut bien réfléchir avant d'ajouter un _package_ à un projet. Renvoi à la future fiche sur la gestion des dépendances.

#### Où trouve-t-on des _packages_?

Introduire la notion de `repo`: CRAN ou Github.

### Comment installer un _package_ issu du CRAN?

- Expliquer qu'on n'a pas accès à Internet, et l'existence du Nexus.
- Préciser que `install.packages()` installe par défaut la dernière version disponible du _package_.
- Comment utiliser `install.packages()` et ses options: `repo`, `lib` et `dependencies`.
- Bien expliquer que dans AUS il faut installer le _package_ dans un répertoire sur lequel on a les droits en écriture. Expliquer `.libPaths` le cas échéant.

### Quelques situations particulières

#### Comment utiliser un _package_ disponible uniquement sur Github?

On peut expliquer facilement comment le faire sur le SSP Cloud. Je ne sais pas si on veut donner une méthode pour le faire dans AUS. On peut peut-être dire que c'est techniquement possible (bien que complexe), mais que ce n'est pas recommandé pour des raisons de sécurité.

#### Comment installer une version particulière d'un _package_?

C'est une utilisation avancée. On peut installer une version particulière un _package_ en faisant une installation manuelle:

- Télécharger la version souhaitée du _package_ en source concerné sur le CRAN.
- Installer ce _package_ avec `install.packages` et `repos = NULL`, en spécifiant bien la librairie.

## Fin du plan temporaire

-->
