# Comment utiliser la documentation `utilitR` {#presentation-utilitr}

## Contenu de la documentation

**Cette documentation vise à aider les agents à réaliser des traitements statistiques usuels avec `R` et à produire des sorties (graphiques, cartes, documents).** Cette documentation présente succinctement les outils les plus adaptés à ces tâches, et oriente les agents vers les ressources documentaires pertinentes. Elle veille en outre à être cohérente avec les recommandations émises par le comité de certification des _packages_ `R` (COPS). En revanche, elle n'aborde pas les outils les plus avancés, notamment ceux utilisés dans un cadre de développement logiciel.

<!-- Cette documentation a pour ambition de répondre à deux questions générales : -->

<!-- * Comment travailler avec `R` à l'Insee ? -->
<!-- * Comment réaliser des tâches standards avec `R` (importation et manipulation de données, exploitation d'enquêtes, graphiques...) ? -->

Trois points importants sont à noter :

* **Cette documentation recommande les outils et les *packages* les plus adaptés au contexte d'utilisation de `R` à l'Insee**. Ces recommandations ne sont pas nécessairement adaptées à d'autres contextes, et pourront évoluer lorsque ce contexte évoluera.
* Cette documentation ne prétend pas être exhaustive ou sans erreurs. **Elle doit être vue comme une mise en commun des connaissances sur `R` que les agents de la statistique publique ont accumulées dans le cadre de leurs activités.**
* **Cette documentation recommande d'utiliser `R` avec  RStudio**, qui apparaît comme la solution la plus simple et la plus complète pour un usage courant de `R`, et qui est par ailleurs le choix effectué par l'Insee.


## Structure de la documentation

**La documentation `utilitR` est composée de fiches regroupées en deux grandes parties** : 

- La première partie explique comment utiliser `R` et  RStudio et les outils associés (`git`, Gitlab) dans les environnements informatiques proposés à l'Insee (AUSv3 et SSP Cloud). 
- La seconde partie est constituée de fiches thématiques expliquant comment réaliser des tâches standards avec `R` (importation et manipulation de données, exploitation d'enquêtes, réalisation de graphiques, rédaction de documents...).

## Contenu des fiches

Chaque fiche porte sur une tâche précise, décrite dans le titre et éventuellement dans les premières lignes. Elle indique quels sont les _packages_ adaptés pour réaliser la tâche en question, et en présente en détail les principales fonctions. Les fiches n'ont toutefois pas la prétention d'être exhaustives ; c'est pourquoi des références figurent à la fin de chaque fiche de façon à orienter le lecteur vers des ressources plus détaillées.

Par ailleurs, les fiches comportent trois types de paragraphes mis en évidence par une icône et une couleur, afin de faciliter la lecture et le repérage des informations importantes.

