# Présentation du projet `utilitR`

## Quel est l'objectif d'`utilitR` ?

**Le projet `utilitR` vise à produire une documentation collaborative et _open source_ sur `R`, destinée en premier lieu aux agents de l'Insee.** Ce projet est parti du constat qu'il est difficile d'apprendre à utiliser `R` pour de multiples raisons : multiplicité de _packages_ faisant plus ou moins la même chose, abondance et éclatement de la documentation (souvent en anglais), difficultés supplémentaires pour effectuer des choix éclairés et adaptés à l'environnement informatique de travail...

Les contributeurs du projet `utilitR` se sont fixés pour objectif de **rassembler  dans un seul document tous les éléments utiles pour l'usage de `R` à l'Insee, en cherchant à couvrir la plupart des cas d'usage courants.** Cette documentation a donc été élaborée en tenant compte du contexte de travail propre à l'Institut. Cette documentation peut évidemment contenir des éléments pertinents pour un usage de `R` en dehors de l'Insee, mais ce n'est pas sa finalité première.

## Quelle est la spécificité d'`utilitR` ?

**Le projet `utilitR` est un projet collaboratif, évolutif, *open source* et ouvert à tous, porté par des agents de l'Insee et du Service Statistique Public (SSP).**
Toute personne qui le souhaite peut modifier la documentation ou la compléter en fonction de ses connaissances et de ses expériences (voir [Comment contribuer au projet `utilitR`](#contribuer)).

Le code source de cette documentation est hébergé sous `Github` et est accessible en cliquant sur [ce lien](https://github.com/InseeFrLab/utilitR).

## Comment contribuer à `utilitR`? {#contribuer}

**Le projet `utilitR` est un projet collaboratif, évolutif, *open source* et ouvert à tous, auquel tous les agents peuvent contribuer.** Le projet est mené par un groupe de contributeurs qui en définissent eux-mêmes le contenu, la structure et le calendrier.
Le dépôt de la documentation est situé sur le compte `InseeFrLab` sur la plateforme `Github` et peut
facilement être retrouvé à [cette adresse](https://github.com/InseeFrLab/utilitR).
Les objectifs et l'approche collaborative du projet `utilitR` sont détaillés dans le document [`Manifeste.md`](https://github.com/InseeFrLab/utilitR/blob/master/Manifeste.md).

**Toute personne qui le souhaite peut modifier ou compléter la documentation en fonction de ses connaissances et de ses expériences**, et toutes les contributions sont les bienvenues : compléments, corrections d'erreur, améliorations, questions... Il n'y a aucun prérequis, et aucun niveau minimal en `R` n'est demandé.

Tout agent intéressé à contribuer au projet est invité à consulter le guide des contributeurs [`CONTRIBUTING.md`](https://github.com/InseeFrLab/utilitR/blob/master/CONTRIBUTING.md).
[Ce guide](https://github.com/InseeFrLab/utilitR/blob/master/CONTRIBUTING.md)
donne également quelques astuces pour les personnes n'étant pas familières 
avec `Github`.

## Contributeurs du projet


::: {.callout-note}

## Contributeurs du projet

Le projet `utilitR` est un projet collaboratif qui a bénéficié des contributions de : 
`r paste0(paste(format(Filter(function(x) !("cph" %in% x$role), desc::desc_get_authors()), include = c("given", "family")), collapse = ", "), ".")`

La coordination est assurée par Pierre-Yves Berrard, Lino Galiana et Olivier Meslin.

Le logo du projet a été réalisé par Anna Schlaifer.

Les contributeurs remercient Julien Taquet et Marc Hufschmitt pour leur
aide précieuse sur la mise en forme du site et de la brochure.

Les contributeurs remercient Arnaud Degorre, Benoît Rouppert, Patrick Sillard
et Sébastien Roux pour leur soutien.
:::

## Licence du projet

L'ensemble du contenu de la documentation est mis à disposition sous
licence libre ([Licence Ouverte 2.0](https://github.com/InseeFrLab/utilitR/blob/master/LICENSE.md)).
Il est donc tout à fait possible de réutiliser une partie ou l'ensemble de la documentation
pour l'adapter à un contexte différent. Les conditions de réutilisation sont explicitées
dans la [licence](https://github.com/InseeFrLab/utilitR/blob/master/LICENSE.md).

Bien que ce ne soit en rien obligatoire,
si vous êtes réutilisateurs de la documentation, n'hésitez pas à vous signaler sur notre [`Github`](https://github.com/InseeFrLab),
vos retours pourraient permettre d'améliorer la documentation, au bénéfice de tous. 
