# Travailler avec `R` à l'Insee

Commentaire OM: Chacune de ces titres aurait vocation à être une section à part entière, et non une sous-section. Je les laisse comme ça pour permettre une lecture facile du plan.

## Fiche démarrage rapide

Quelques idées en vrac:

* où clique-t-on pour accéder à Rstudio?
* Où se trouve le Gitlab?
* Comment on se crée une librairie avec des droits en écriture?
* Comment on installe un `package`?

Cette fiche démarrage rapide pourrait/devrait être la première section de la partie faire du `R` à l'Insee. Elle recoupe peut-être partiellement la partie sur la présentation de l'environnement logiciel.

## Présentation de l'environnement logiciel

Présentation succincte des outils à l'attention des novices (en un petit tableau): R, Rstudio, git, Gitlab, Rtools, Rmarkdown...


## Comment (bien) utiliser `R` et `Rstudio` à l'Insee?

### Où faire du `R` à l'Insee

* Comment on se connecte à AUS;
* Comment on lance Rstudio.

Reprendre et adapter la partie projets collaboratifs avec `R` de la formation Travail Collaboratif sous R.

### Comment personnaliser sa configuration `R` et `Rstudio` sous AUS?

Parler du fichier `.Rprofile`, et dire ce qui peut être configuré.

### Comment installer des `packages`?

* Comment on se crée une librairie avec des droits en écriture?
* Expliquer le fonctionnement des miroirs à l'Insee.

### Guides des bonnes pratiques sur `R`

Reprendre:

* le guide des bonnes pratiques rédigé par Lino;
* les recommandations figurant dans le `CONTRIBUTING.md` du dépôt Gitlab;
* le document de Benoît "Savoir compter, savoir coder";
* les éléments dont Pierre dispose.

## Comment utiliser `Git` avec `R`?

### Des bases de `Git`

Reprendre la partie 4.2 de la formation Travail Collaboratif sous R.

### Où mettre son dépôt local `Git`

### Utiliser `Git` l'interface `Rstudio`

## Comment travailler à plusieurs avec Gitlab?

### Présentation du Gitlab interne

### Configurer son accès à Gitlab (SSH, Putty etc.)

Reprendre la partie 4.4 de la formation Travail Collaboratif sous R.

### Travailler avec Gitlab

Les issues, les branches, les merge requests.

Reprendre la partie 4.3 de la formation Travail Collaboratif sous R.

### Les bonnes pratiques avec `Git` et Gitlab

Reprendre la partie 4.5 de la formation Travail Collaboratif sous R.

## D'autres idées plus avancées

* Comment utiliser l'intégration continue sur Gitlab.
* Comment développer des packages en `R` à l'Insee (reprendre la partie 7 de la formation Travail Collaboratif sous R)

