# Comment travailler avec R à l'Insee ?

## Démarrage rapide de `R` à l'Insee

- où clique-t-on pour accéder à Rstudio? Description rapide des environnements: local, AUS, PF innovation.
- Comment on installe un _package_?
  - Comment on crée un projet Rstudio?
  
  ## Utiliser `R` et `Rstudio` à l'Insee?
  
  ### Les différents environnements d'usage de `R` à l'Insee
  
  - Description rapide des environnements: local, AUS, PF innovation. Avantages/inconvénients.
- Comment je choisis mon environnement de travail en fonction de ce que je veux faire.
- Bien expliquer que le choix de l'environnement de travail peut impliquer des pratiques différentes.

#### Utiliser `R` en local

- Comment on installe `R` et Rstudio.
- Comment on lance Rstudio.

#### Utiliser `R` sous AUS

- Comment on se connecte à AUS;
- Comment on lance Rstudio.

#### Utiliser `R` sur la PF innovation

- Comment on se crée un compte sur la PF innovation;
- Comment on lance un container Rstudio.

### Utiliser les projets Rstudio pour structurer son travail

Reprendre (en version très allégée) la partie 3 de la formation Travail Collaboratif sous `R`.

## Personnaliser sa configuration

Il faut probablement distinguer les différents environnements.
Parler du fichier `.Rprofile`, et dire ce qui peut être configuré.

## Les _packages_ `R`

### Installer des _packages_

- Quelles sont les sources pour les _packages_? CRAN, Github...
- Expliquer qu'il y a des miroirs pour AUS;
- Expliquer comment installer un _package_ (et aussi *binary* _versus_ *source*).

### Choisir un _package_

Fiche en préparation par Romain Lesur.
Cette partie peut être ici, ou transférée dans la partie Fiches thématiques.

## La gestion de version

### Utiliser Git et Rstudio

#### Introduction à Git

- Des bases de `Git`: Reprendre la partie 4.2 de la formation Travail Collaboratif sous R.

#### Git dans Rstudio

- Où mettre son dépôt local `Git` (en local et dans AUS)
- Utiliser `Git` avec l'interface `Rstudio`

### Le Gitlab interne

- Présentation du Gitlab interne
- Configurer son accès à Gitlab (SSH, Putty etc.)
- Comment travailler à plusieurs avec Gitlab? Reprendre la partie 4.4 de la formation Travail Collaboratif sous R.

## Se former à `R` à l'Insee