# Des boîtes colorées

En HTML/CSS (mais pas seulement), les deux principaux types de rendus (`display`) sont `block` et `inline`. Par défaut, un élement qui a son `display` de type `block` prend toute la largeur et "repousse" les autres élements vers le haut et le haut. Un élément qui a un `display` de type `inline` se comporte "en ligne" : les élements qui le précédent et le suivent le "collent" horizontalement.

Tout ça pour dire que pour faire un bloc, il nous faut un élément avec un `display` de type `block`... ok, c'était trivial.

En HTML, l'élément "neutre" de type `block` est un `<div></div>` (l'élement inline neutre est le `<span></span>`).

Des éléments équivalents existent en markdown, voir <https://pandoc.org/MANUAL.html#divs-and-spans>.

Si on écrit en markdown :

```markdown
::: cops
Recommandation du COPS
:::
```

le HTML généré par Pandoc sera un élement `div` :

```html
<div class="cops">
<p>Recommandation du COPS</p>
</div>
```

L'utilisation d'une classe (ici `cops`) va être très utile car elle va nous permettre d'appliquer un style uniforme à tous les éléments de classe `cops`.

Maintenant, faisons un peu de CSS.

Une des notions fondamentales est celle de sélecteur : il s'agit d'une règle appliquée par le navigateur pour rechercher des éléments (pour une référence exhaustive sur ce sujet, voir <https://developer.mozilla.org/fr/docs/Web/CSS/S%C3%A9lecteurs_CSS>).

Dans notre cas, on va faire simple et sélectionner tous les éléments de classe `cops`. Pour cela, en CSS, on va commencer par écrire cela :

```css
.cops {
  /* On va mettre nos déclarations de style ici */
}
```

En CSS, le point (`.`) qui préfixe un nom sert à sélectionner tous les éléments d'une certaine classe. Dans l'exemple ci-dessus, on sélectionne tous les éléments de classe `cops` grâce au sélecteur `.cops`.

Première chose qu'on peut faire : mettre une couleur de fond avec la propriété CSS `background`.

Exemple :

```css
.cops {
  background: #ee98fb;
}
```

```{css, echo=FALSE}
.cops1 {
  background: #ee98fb;
}
```

::: cops1
Recommandation du COPS
:::


On peut certainement vouloir lui rajouter un peu de padding pour mettre un peu plus de couleur autour du texte.

```css
.cops {
  background: #ee98fb;
  padding: 12pt;
}
```

```{css, echo=FALSE}
.cops2 {
  background: #ee98fb;
  padding: 12pt;
}
```

::: cops2
Recommandation du COPS
:::

On peut également arrondir les angles :

```css
.cops {
  background: #ee98fb;
  padding: 12pt;
  border-radius: 15px;
}
```

```{css, echo=FALSE}
.cops3 {
  background: #ee98fb;
  padding: 12pt;
  border-radius: 15px;
}
```

::: cops3
Recommandation du COPS
:::

Et si on aime bien le material design, on peut même rajouter une ombre à la boîte :

```css
.cops {
  background: #ee98fb;
  padding: 12pt;
  border-radius: 15px;
  box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
  margin: 12px 0;
}
```

```{css, echo=FALSE}
.cops4 {
  background: #ee98fb;
  padding: 12pt;
  border-radius: 15px;
  box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
  margin: 12px 0;
}
```

::: cops4
Recommandation du COPS
:::

Si on est un peu old school, on peut préférer une bordure  :

```css
.cops {
  background: #ee98fb;
  padding: 12pt;
  border-radius: 15px;
  border: 5px solid #883997;
}
```

```{css, echo=FALSE}
.cops5 {
  background: #ee98fb;
  padding: 12pt;
  border-radius: 15px;
  border: 5px solid #883997;
}
```

::: cops5
Recommandation du COPS
:::

Pour aller plus loin, la meilleure référence est MDN <https://developer.mozilla.org/fr/>.
