# Manifeste du projet `UtilitR`

## Qu'est-ce que le projet `UtilitR`?

**Le projet `UtilitR` vise à produire une documentation collaborative sur le logiciel `R` prioritairement à l'usage des agents de l'Insee.** Cette documentation s'adresse ainsi à tous les agents amenés à utiliser `R` dans le cadre de leur poste. C'est pourquoi elle a été élaborée en prenant en compte le contexte de travail propre à l'institut. Cette documentation peut également contenir des éléments pertinents pour un usage de `R` en dehors de l'Insee, mais ce n'est pas sa finalité première.

## Pourquoi avons-nous lancé `UtilitR` ?

Le projet `UtilitR` est parti du constat qu'il est difficile d'apprendre à utiliser `R` pour de multiples raisons: multiplicité de _packages_ faisant plus ou moins la même chose, abondance et éclatement de la documentation (souvent en anglais), difficultés supplémentaires pour effectuer des choix éclairés et adaptés à l'environnement informatique de travail... **Nous nous sommes donc fixés pour objectif de rassembler tous les éléments utiles pour l'usage de `R` à l'Insee dans un seul document, en cherchant à aborder le plus grand nombre possible de cas d'usage.** 

## Quelle est la spécificité du projet `UtilitR`?

**Le projet `UtilitR` est un projet collaboratif, évolutif et ouvert à tous, auquel tous les agents peuvent contribuer.** Tout agent qui le souhaite peut modifier la documentation ou la compléter en fonction de ses connaissances et de ses expériences (voir [Comment fonctionne le projet `UtilitR`?]).

Cette documentation ne prétend pas être exhaustive ou sans erreurs. **Elle doit être vue comme une mise en commun des connaissances que les agents détiennent sur l'usage de `R`.**

## Quelle est la place du projet `UtilitR` à l'Insee?

**Le projet `UtilitR` est porté par les agents du réseau LS<sup>2</sup> (Libre service statistique) de l'Insee.** La documentation `UtilitR` ouverte, collaborative et adaptée au contexte de travail de l'institut vise à être cohérente avec les recommandations émises par le comité de certification des _packages_ `R` (COPS) et complète les supports du projet `USSR` (LIEN A AJOUTER).

## Quelles sont les valeurs du projet `UtilitR`?

**Le projet `UtilitR` repose sur cinq principes: transparence, ouverture, bienveillance, exigence, reproductibilité.**

- Transparence: l'ensemble du projet est librement accessible sur le [dépôt Gitlab](https://gitlab.com/linogaliana/documentationR), sous licence libre;
- Ouverture: **tout agent de l'Insee qui le souhaite peut rejoindre le projet à tout moment**. Les modalités de contribution peuvent prendre différentes formes, détaillées dans le [guide des contributeurs](CONTRIBUTING.md);
- Bienveillance: toutes les idées, initiatives et propositions sont les bienvenues, et les contributeurs veillent à se soutenir les uns les autres;
- Exigence: les modifications de la documentation sont systématiquement soumises à une revue par les contributeurs du projet et ne sont acceptées que lorsqu'elles rencontrent une large approbation;
- Reproductibilité: les exemples développés dans la documentation doivent être reproductibles. 

## Comment fonctionne le projet `UtilitR`?

Tout agent intéressé à contribuer au projet `UtilitR`, quelles que soient ses motivations - volonté de s'auto-former, recherche d'une réponse à une question précise, ou encore envie de partager ses connaissances - est cordialement invité à consulter le [guide des contributeurs](CONTRIBUTING.md), le cas échéant à créer un compte sur [Gitlab](https://gitlab.com) et à se manifester auprès des contributeurs listés [ici](https://gitlab.com/linogaliana/documentationR/-/project_members). Il pourra également poser toutes les questions qu'il aura [ici](https://gitlab.com/linogaliana/documentationR/-/issues). Le groupe de contributeurs communique également au travers d'une [application de tchat de l'État](www.tchap.gouv.fr).

Il s'agit d'un projet collaboratif reposant pour l'heure sur l'initiative d'une poignée d'agents de l'Insee. Le groupe de contributeurs définit ainsi lui-même le calendrier du projet, en fonction des impératifs professionnels, et s'auto-assigne les objectifs en termes de contenu et de structure. Cette organisation horizontale implique donc un effort de concertation, les règles de décision étant fixées à la majorité. Le projet, une fois atteint une taille jugée critique, devra viser peut-être un mode de gouvernance plus verticale ; il n'en demeure pas moins que la vision et l'esprit collaboratif auquel les contributeurs sont extrêmement attachés sont constitutifs de ce projet et en font sa spécificité et sa force.

Ce projet trouve ses racines dans la période de confinement qui a affecté le pays au printemps 2020 ; ce contexte explique une partie des choix méthodologiques et techniques qui ont été faits, comme par exemple le fait d'opter pour un dépôt accessible librement sur Internet. Il est surtout porté par la volonté de prendre le meilleur d'une situation difficile, en cherchant à préparer le futur et à favoriser des mouvements de solidarité et de bienveillance au sein de l'institut - dans un cadre bien précis, mais néanmoins essentiel pour l'institut, celui de l'usage accru de `R` dans les missions quotidiennes des agents de l'Insee.


## Chutes de texte à réutiliser

(au travers par exemple de l'ouverture d'une _issue_ - une sorte de ticket propre à l'environnement collaboratif choisi pour le développement de ce projet, ou encore mieux en instruisant les questions qu'ils se posent et en décrivant les réponses dans la documentation)
