[project]
name = "utilitr"
r_version = "4.6"

# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
# Example: { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
repositories = [
    { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
    { alias = "CRAN", url = "https://cran.r-project.org" },
]

# A list of packages to install and any additional configuration
# Examples:
    # "dplyr",
    # {name = "dplyr", repository = "CRAN"},
    # {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
dependencies = [
    "dplyr",
    "data.table",
    "stringr",
    "rmarkdown",
    "quarto",
    "duckdb",
    "arrow",
    "kableExtra",
    { name = "doremifasol", git = "https://github.com/InseeFrLab/DoReMIFaSol", branch = "master" },
    { name = "doremifasolData", git = "https://github.com/InseeFrLab/DoReMIFaSolData", branch = "main" },
    "targets",
    "openxlsx",
    "readODS",
    "tidyr",
    "dbplyr",
    "rex",
    "sf",
    "lubridate",
    "parsedate",
    "zoo",
    "ggplot2",
    "dygraphs",
    "downlit",
    "xml2",
    "FactoMineR",
    "factoextra",
    "lintr",
    "httr2",
    { name = "melodi", git = "https://github.com/inseefrlab/melodi", branch = "main" },
    { name = "insee", git = "https://github.com/pyr-opendatafr/R-Insee-Data", branch = "master" },
    { name = "OECD", git = "https://github.com/expersso/OECD", branch = "master" },
]
