# Qualité du code {#code-quality}

## Tâches concernées et recommandations

Blabla

::: {.callout-recommandation .icon}
Blabla
:::

Cette partie détaille de manière plus étendue les éléments enseignés
dans le cadre d'une formation aux bonnes pratiques 
construite par l'Insee et dont les supports ont été ouverts à 
[cette adresse](https://inseefrlab.github.io/formation-bonnes-pratiques-R/#/title-slide).


## Enjeux


Lors de l'apprentissage d'un langage, il est assez naturel de voir le code d’une manière très fonctionnelle : on désire réaliser une tâche donnée — par exemple nettoyer des champs textuels — et
on va donc assembler dans un script des bouts de code, souvent trouvés sur internet, jusqu’à obtenir un projet qui réalise la tâche voulue.
La structure du projet importe assez peu, tant qu’elle permet d’importer et traiter les données nécessaires à la tâche en question.

Si cette approche flexible et minimaliste fonctionne très bien lors de la phase d’apprentissage, il est malgré tout indispensable de s’en détacher progressivement à mesure qu’on progresse et que l’on peut être amené à réaliser des projets collaboratifs ou amenés à durer dans le temps.

Lorsqu'on travaille avec R, il est important de considérer
le code non seulement comme un outil pour effectuer des tâches,
mais aussi comme un __moyen de communiquer__
nos méthodes et résultats à d'autres personnes.
En adoptant des bonnes pratiques, on améliore la lisibilité
et la compréhension d'un code, ce qui facilite la collaboration avec
les réutilisateurs du code mais aussi auprès de publics, comme les
chercheurs, désirant 
comprendre les traitements mis en oeuvre.

La __lisibilité__ et la __maintenabilité__ du code
sont des aspects clés pour assurer la qualité d'un projet statistique.
Les bonnes pratiques aident à écrire du code clair et structuré, ce qui fait gagner du temps pour s'approprier un code, corriger des erreurs ou apporter des modifications à un code.
Un code étant plus souvent lu qu'écrit[^1]

[^1]: Cette phrase très connue est une citation de Guido Van Rossum, le créateur
de `Python`. `R` comme `Python` tous deux des langages conçus pour être plus
transparents que des langages bas niveaux comme `C`. 

La __réutilisation__ d'un code ou de productions associées à du code,
comme des bases
de données, peut être grandement facilitée en adoptant des bonnes pratiques.


Grâce aux bonnes pratiques, nous pouvons nous assurer que notre
travail est __transparent__ et facilement __vérifiable__.
Cette exigence de reproductibilité, notion centrale dans le domaine de la recherche
scientifique, s'applique également
dans d'autres domaines où la transparence méthodologique est cruciale pour la validité et la fiabilité des résultats. Un code de qualité facilite ainsi 
la vérification et la reproduction de nos résultats par d'autres personnes.
A l'image du processus de revue par les pairs (_peer review_)
dans le domaine scientifique,
se développent des revues de code (_code review_) qui favorisent la production
d'un code de qualité. 


## Adopter les standards communautaires

### Enjeux

> *"Good coding style is like correct punctuation: you can manage without it, butitsuremakesthingseasiertoread"*

>
> [Tidyverse Style Guide](https://style.tidyverse.org/)

Tout comme la correction de la ponctuation peut rendre un texte plus facile à lire,
une bonne pratique de codage peut rendre notre code plus facile à comprendre
à maintenir et à réutiliser.

Il est également important de respecter les conventions du langage dans lequel le code est rédigé. Cela peut inclure des normes de formatage telles que l'indentation et la mise en forme, ainsi que des conventions de nommage telles que les noms de variables et de fonctions. En utilisant les conventions standardisées du langage, nous pouvons rendre notre code plus cohérent et plus facile à comprendre pour les autres personnes travaillant dans ce langage.

Il existe deux guides de référence qui exposent les conventions de la communauté
`R` concernant la qualité du code :
le [_`Tidyverse` style guide_](https://style.tidyverse.org/) et
le [_`Google` style guide_](https://google.github.io/styleguide/Rguide.html).
Ce guide propose des conseils sur la façon d'écrire du code clair et structuré en utilisant les bonnes pratiques recommandées pour le langage R. Il peut être utile de se référer à ce guide pour s'assurer d'adopter des bonnes pratiques en matière de codage en R.

. . .

- Respecter les [conventions]{.orange} du langage dans lequel il est rédigé

. . .

- Il existe un **guide de référence** pour bien coder en `R` : le [Tidyverse style guide](https://style.tidyverse.org/index.html).


## :one: Adopter les standards communautaires {.smaller}

Deux outils pratiques aident à respecter les standards :

1. [**_linter_**]{.orange} : programme qui vérifie que le code est __formellement__ conforme à un certain _guidestyle_
    + signale problèmes formels, sans corriger 

. . .

2. [**_formatter_**]{.orange} : programme qui reformate un code pour le rendre conforme à un certain _guidestyle_
    + modifie directement le code

. . .

::: {.callout-tip}

- [Exemples d’erreurs repérées]{.blue2} par un _linter_ : 
    + lignes de code trop longues ou mal indentées, parenthèses non équilibrées, noms de fonctions mal construits…
- [Exemples d’erreurs __non__ repérées]{.blue2} par un _linter_ :
    + fonctions mal utilisées, arguments mal spécifiés, structure du code incohérente, code insuffisamment documenté…
:::


<!--------- VERSION SITE WEB 
1. Un [**_linter_**]{.orange} est un programme qui vérifie que le code est __formellement__ conforme à un certain _guidestyle_, et signale les erreurs. En revanche, un _linter_ ne modifie pas directement le code et ne repère pas les erreurs de fond.

  &#8627; Exemples d’erreurs repérées par un _linter_ : lignes de code trop longues ou mal indentées, parenthèses non équilibrées, noms de fonctions mal construits…
  &#8627; Exemples d’erreurs __non__ repérées par un _linter_ : fonctions mal utilisées, arguments mal spécifiés, structure du code incohérente, code insuffisamment documenté…
. . .

2. Un [**_formatter_**]{.orange} est un programme qui reformate un code source pour le rendre conforme à un certain _guidestyle_. Par définition, un _formatter_ modifie directement le code.
-------->

## :one: Adopter les standards communautaires {.smaller}

<br>

Dans le cas de {{< fa brands r-project >}} : 

- le [_linter_]{.orange} à utiliser est le _package_ [`lintr`](https://github.com/r-lib/lintr);
- le [_formatter_]{.orange} à utiliser est le _package_ [`styler`](https://github.com/r-lib/styler).
    + Existe également le _package_ [`formatR`](https://github.com/yihui/formatR).

## :two: Utiliser des fonctions {.smaller}

::: {.callout-important}
## Règle d'or

Il faut utiliser une [**fonction**]{.red2} dès qu'on utilise une même
portion de code plus de deux fois ([**_don't repeat yourself_ (DRY)**]{.red2})
:::

- [Limite les risques d'erreurs]{.orange} liés aux copier/coller
- Rend le code [plus lisible]{.orange} et [plus compact]{.orange}
- [Un seul endroit]{.orange} du code à modifier lorsqu'on souhaite modifier le traitement
- Facilite la [réutilisation]{.orange} et la [documentation]{.orange} du code !

. . .

::: {.callout-tip}
## Règles pour écrire des fonctions **pertinentes**

- Une tâche = une fonction ;
- Une tâche complexe = un enchaînement de fonctions réalisant chacune une tâche simple ;
- Limiter l'utilisation de variables globales.

:::

## :three: Documenter son code

- Grands principes :
  - Documenter le [__pourquoi__]{.orange} plutôt que le [__comment__]{.orange} ;
  - Privilégier l'auto-documentation via des [**nommages pertinents**]{.orange}.

. . .

::: {.callout-tip}
## Comment bien documenter un script ?

- [**Minimum**]{.orange} 🚦 : commentaire au début du script pour décrire ce qu'il fait ;
- [**Bien**]{.orange} 👍 : commenter les parties "délicates" du code ;
- [**Idéal**]{.orange} 💪 : documenter ses fonctions avec la syntaxe `roxygen2`.

:::


## :four: Pas d'ambiguïté sur les _packages_ utilisés {.smaller}

- Deux fonctions peuvent avoir le [__même nom__]{.orange} dans des [__packages différents__]{.orange}

. . .

- `R` utilise par défaut la librairie chargée le plus récemment

. . .

- Erreurs difficiles à repérer car il est nécessaire d'exécuter le code

. . .

- Recommandation : indiquer explicitement le _package_ : notation `package::fonction()`
    + Exemple : `dplyr::filter()`

:::{.callout-tip}
## Exemple
- `package1` et `package2` contiennent chacun une fonction appelée `superFonction`.
- Si `package2` est chargé après `package1`, alors `superFonction` désigne par défaut la fonction de `package2`.
- Mieux vaut noter `package1::superFonction` et `package2::superFonction`
:::


<!------ Pour la version blog

Des packages contenant des fonctions homonymes peuvent être à l’origine de conflits. Ceci est dû au fait que R utilise par défaut la fonction du package chargé le plus récemment.

    Exemple: si les packages package1 et package2 contiennent chacun une fonction appelée superFonction, et si package2 est chargé après package1, alors superFonction désigne par défaut la fonction de package2.

Cette ambiguïté peut entraîner des erreurs difficiles à repérer, car le code donne l’impression d’appeler la bonne fonction. C’est pourquoi il est recommandé d’indiquer explicitement le package utilisé en utilisant la notation package::fonction() (par exemple dplyr::filter()).

:::{.callout-tip}
## Le_package_[`conflicted`](https://github.com/r-lib/conflicted#conflicted)

Le_package_`conflicted` aide à gérer les conflits de_packages_de manière fluide.
:::
------>


## Ressources supplémentaires

<br>

- [_R Packages_](https://r-pkgs.org/man.html) par Hadley Wickham and Jenny Bryan
- Une [présentation très bien faite](https://mitmat.github.io/slides/2022-05-26-egu/code-data-open-science.html#1)
- [Un cours complet](https://eliocamp.github.io/reproducibility-with-r/) sur la reproductibilité avec `R`
- L'équivalent `Python` en [3A d'ENSAE](https://ensae-reproductibilite.netlify.app/about/)


## Exercices