# Fiches de documentation

Commentaire OM: Chacune de ces titres aurait vocation à être une section à part entière, et non une sous-section. Je les laisse comme ça pour permettre une lecture facile du plan.

## Manipuler des données (`dplyr` et `data.table`)

## Créer ses propres fonctions

Reprendre la partie 6 de la formation Travail collaboratif avec R.

## Ecrire des tables intermédiaires en `R` (`fst`)

## Exporter des données (quels packages?)

## Faire des graphiques (`ggplot2`)

## Traiter des données textuelles (`stringr` et une introduction aux `regex` en `R`)

## Utiliser un SGBD en `R` (`DBI` et autres drivers)

## Réaliser des cartes

### Tâches concernées et recommandations

L'utilisateur souhaite A COMPLETER.



::: recommandation
**Recommandations de l'Insee**

* Pour faire des cartes, il est recommandé d'utiliser des outils cartographiques.

:::

### Introduction à la cartographie avec `R` et `sf`/`sp`/`le bon package`




### Bonnes pratiques



### Ressources

* la doc des packages;
* les supports de formation à l'Insee;
* les supports de formation externes;
* les bons sites ressources (tutoriels, galeries, forums...)



## Rédiger des documents en `R` (`Rmarkdown`)
