# Se documenter sur `R`

## Tâches concernées et recommandations

Vous souhaitez vous y retrouver dans les différents niveaux de documentation que l'on trouve sur `R`, afin de répondre à un besoin précis ou d'enrichir vos compétences. La documentation concernant `R` est luxuriante, à son image. L'objet de cette fiche est de vous permettre de vous y retrouver. Trois cas sont à distinguer:

* vous savez de quelle fonction vous avez besoin mais ne savez pas comment elle fonctionne;
* vous savez ce que vous voulez faire mais ne savez pas quelle fonction ou _package_ utiliser;
* vous n'avez pas en tête un projet particulier mais voulez découvrir ou vous tenir à jour sur les possibilités de `R`. 

::: {.recommandation}


* si vous souhaitez en savoir davantage sur l'utilisation d'une fonction dont vous connaissez l'existence, il est souvent suffisant de consulter la documentation de la fonction en exécutant `?nomFonction` dans RStudio ;
* si vous cherchez de l'information sur l'utilisation d'un _package_ particulier, regardez si une __vignette__ est disponible ;
* si vous souhaitez explorer des pans de l'écosystème `R` qui sont complètement nouveaux pour vous, vous tenir informé des nouveautés ou évoluer dans vos pratiques, vous pouvez faire deux choses :
    - consulter la ou les fiches correspondante(s) de la documentation `utilitR` ;
    - rejoindre les communautés d'utilisateurs qui vous correspondent.
:::


## Vous savez quelle fonction utiliser

**Si vous savez quelle fonction utiliser mais ne savez pas comment cette dernière fonctionne, il est souvent suffisant de regarder la documentation de la fonction.** Il ne faut pas hésiter à se référer très fréquemment à cette documentation : c'est la solution la plus rapide pour retrouver le nom d'une option particulière, ou sa signification. Pour cela, il suffit d'exécuter `?NomFonction` dans la console de RStudio (sans espace entre le `?` et le nom de votre fonction). Par exemple, si vous souhaitez réaliser un export en csv avec la fonction `write.csv`, exécutez l'instruction :

REMETTRE LE CHUNK ICI 

La documentation de la fonction apparaîtra dans le panneau en bas à droite de RStudio. Pour chaque fonction, vous allez retrouver :

* une description de son fonctionnement ;
* les différentes options, ainsi que les valeurs par défaut ;
* des exemples.

**Il est important de noter que la fonction `?` ne fonctionnera que si le _package_ qui contient la fonction a été chargé avec l'instruction `library`.** Si vous n'êtes pas sûr que le _package_ ait été chargé (par exemple parce que vous avez oublié son nom), vous pouvez utiliser le double point d'interrogation (`??`) afin de chercher un mot dans tous les fichiers d'aide de votre poste. Ainsi `??select` vous renverra la liste de tous les fichiers d'aide contenant le mot `select`. Toutefois, cette méthode n'est pas la plus recommandée, car elle peut aboutir à un nombre de résultats très importants.

## Vous savez ce que vous voulez faire, mais c'est tout

**Si vous savez ce que vous voulez faire, mais vous ne savez pas comment le faire, la première étape consiste à vérifier si documentation `utilitR` contient une fiche qui porte sur votre besoin.** Cette documentation est conçue pour couvrir la plupart des usages courants de `R`, il est donc probable que vous pouvez y trouver de premiers éléments.

Si ce n'est pas le cas, vous pouvez vous référer à la fiche [Comment choisir un _package_\ ?](#choisir-package), afin de déterminer s'il est opportun de choisir un _package_, et si oui lequel. Une fois le _package_ sélectionné, pour comprendre comment il fonctionne, commencez par rechercher si des _vignettes_ sont disponibles. __Une vignette est une page d'aide attachée à un _package_**, qui permet d'aller au-delà de la documentation fonction par fonction que nous avons vue ci-dessus. Pour voir quelles _vignettes_ sont disponibles, vous pouvez utilisez la fonction `vignette`. En utilisant l'option _package_, vous allez pouvoir lister toutes les _vignettes_ d'un _package_ donné, puis appeler celle que vous le souhaitez directement par son nom. Ainsi, `vignette(package="dplyr")` va lister les cinq _vignettes_ du _package_ `dplyr`, puis `vignette("two-table")` afficher la _vignette_ consacrée aux verbes à deux tables.
## Vous voulez découvrir des choses sur `R`

__L'écosystème `R` est extrêmement vaste et évolue rapidement, si bien que la difficulté peut parfois être liée au fait de savoir qu'une fonctionnalité existe plutôt qu'à son utilisation proprement dit.__ Par conséquent, il est utile de consacrer du temps à se tenir informé de l'actualité et à échanger avec d'autres utilisateurs de `R`.

Les utilisateurs de `R` forment de nombreuses communautés qui se superposent. Selon votre niveau en `R`, votre niveau en anglais et les sujets qui vous intéressent, vous pouvez rejoindre certaines de ces communautés. En voilà quelques unes :

* à l'Insee, en plus des groupes qui peuvent s'être formés localement, on peut trouver des échanges sur [tchap](https://tchap.gouv.fr/), dans le canal `#salon Insee - Outils stats V2` ;
* au sein du service statistique publique, toujours sur Tchap, des communautés sont actives sur les canaux `#langage R` ainsi que `#spyrales` (orienté formation) ;
* au niveau francophone, la communauté est très présente sur le [slack](https://fr.wikipedia.org/wiki/Slack_(plateforme)) [r-grrr](r-grrr.slack.com) (inscription nécessaire mais libre) ;
* au niveau mondial, de nombreux échanges ont lieu sur [twitter](https://twitter.com) (hashtag [#rstats](https://twitter.com/search?q=%23rstats&src=typed_query)).


## Pour en savoir plus

* [site détaillant les fonctionnalités d'aide incluses dans R](https://www.r-project.org/help.html)
