# Configurer git sur son poste de travail

## Tâches concernées et recommandations

L'utilisateur souhaite versionner son code depuis son poste de travail, en ayant recours pour cela à un dépôt distant (l'utilisation du logiciel Git en local relève de l'usage habituel du logiciel), et de manière générale réaliser les manoeuvres décrites dans la fiche "Utiliser Git avec RStudio").

::: {.recommandation data-latex=""}
* Pour interagir avec un dépôt Git distant, l'utilisateur a le choix entre deux protocoles de connexion, `SSH` ou `https`
* Malgré de forts arguments en matière d'ergonomie une fois configuré, le protocole `SSH` est déconseillé en faveur du protocole `HTTPS` (qui ne requiert que de configurer un mot de passe sur le dépôt distant)
:::

## Les différents dépôts distants possibles

On en distingue principalement deux :
* Github (accessible sur le Web, à l'adresse [https://github.com]) ;
* Gitlab qui se décline pour l'utilisateur sous différentes formes
Gitlab étant la solution la plus déclinée, on prendra comme cas d'usage l'utilisation d'un dépôt distant sur une solution de type Gitlab. Néanmoins, la procédure pour configurer l'interaction avec un dépôt sur Github est très similaire.

## Installer Git sur son poste de travail

Pour installer Git, il suffit désormais d'installer le logiciel récupéré sur le [site web officiel](http://git-scm.com/download/win). Une fois le logiciel installé, il est possible de le retrouver dans le menu Démarrer, rubrique Git. L'utilisateur y trouvera plusieurs outils, dont un outil de ligne de commande (`Git Bash`) et une interface (`Git GUI`).
