# Demander de l'aide sous `R`

## Tâches concernées et recommandations

Votre code ne fait pas ce que vous voudriez qu'il fasse et vous ne comprenez pas ce qui ne va pas. Il peut alors être opportun de se faire aider. Cette fiche détaille à qui vous pouvez demander de l'aide et comment le faire pour que vous puissiez résoudre votre problème.

::: {.recommandation}
* commencer par isoler le problème en le reproduisant sur un jeu de données publiques (_iris_, _cars_,... ) ;
* si vous avez un message d'erreur, copier le dans un moteur de recherche ;
* posez votre question sur [Stackoverflow](https://stackoverflow.com/), un forum ou un service de messagerie instantanée en incluant le code permettant de reproduire l'erreur.
:::

## Commencer par isoler le problème

Cette étape est essentielle : quand on rencontre un problème en travaillant sur un programme, les sources d'erreurs potentielles sont multiples et pas évidentes à identifier si on s'en tient aux messages d'erreurs. En particulier, le problème peut venir d'un jeu de données mal maîtrisé : présence de valeurs manquantes, valeurs hors normes, problème de format, *group_by* qui traîne... Il peut également se situer à une étape intermédiaire de votre programme, et non à l'étape que vous venez de rajouter, ou qui vous semble problématique. 

Vous pouvez donc commencez par exécuter votre programme pas-à-pas en vérifiant à chaque étape si le résultat intermédiaire correspond à ce que vous attendez, jusqu'à trouver l'instruction qui pose problème. Ceci fait, commencez un nouveau script et essayez de reproduire ce que vous souhaitez faire, mais avec un jeu de données publique (_iris_, _cars_, _ggplot2::diamonds_...). Cette approche se retrouve souvent, sur internet, sous l'acronyme *MWE* ([*minimum working example*](https://en.wikipedia.org/wiki/Minimal_working_example) ou exemple minimal reproductible). L'intérêt de cette opération est double :

* si cela fonctionne, vous savez que le problème provient de votre jeu de données. Il faut donc vérifier à nouveau les étapes précédentes du programme ;
* si cela ne fonctionne pas vous disposez maintenant d'un exemple que vous allez pouvoir utiliser pour poser votre question.

Si vous ne trouvez pas jeu de données adapté à votre problème, vous pouvez en constituer un nouveau à l'aide de la fonction `tibble::tibble()` ou `data.frame()`. 

Dans bien des cas, isoler le problème va vous permettre de le résoudre. Si ce n'est pas le cas, il vous faut alors aller chercher de l'aide.

## Chercher de l'aide

### La question a-t-elle déjà été posée ?

La première chose à faire est de vérifier que la question n'a pas déjà été posée : en particulier quand on débute, il est rare de rencontrer un problème dont la solution ne figure pas déjà en ligne. Si vous avez un message d'erreur, vous pouvez le copier/coller dans un moteur de recherche. Si vous n'en avez pas, le plus efficace est d'essayer de formuler votre problème en anglais et de rechercher ça dans un moteur de recherche générique, ou directement sur le moteur de recherche de [Stackoverflow](stack-overflow). 

### Où chercher de l'aide ?

Selon le type de problème, votre niveau en anglais et le temps que vous êtes prêts à attendre, vous pouvez chercher de l'aide aux endroits suivants :

* [Stackoverflow](https://stackoverflow.com/) (SO) est un site de questions/réponses sur de nombreuses thématiques liées à l'informatique. C'est la façon la plus efficace d'obtenir une réponse rapide, y compris sur des sujets particulièrement complexes, pour peu qu'on accepte de se plier au formalisme demandé (voir [plus bas](Zoom sur stackoverflow)) ;
* le [groupe slack grrr](https://r-grrr.slack.com) (francophone) dispose d'un canal `#questions` qui est assez réactif. Toujours en français, le forum du [Cirad](https://fr.wikipedia.org/wiki/Centre_de_coop%C3%A9ration_internationale_en_recherche_agronomique_pour_le_d%C3%A9veloppement) héberge une importante communauté `R`. S'il n'est plus la référence qu'il a longtemps été, il est toujours actif ;
* En interne SSP, il est possible de trouver de l'aide sur la messagerie instantanée [Tchap](https://tchap.gouv.fr/), sur le canal `#langage R` ;
* Enfin, en interne Insee, il y a également un canal dédié sur Tchap (`#Insee - Outils stats v2`)

Ces différentes plateformes sont classées en fonction de leur nombre d'utilisateurs, ce qui a un impact mécanique sur la rapidité des réponses et la chance de tomber sur un utilisateur maîtrisant parfaitement le domaine sur lequel vous cherchez Cependant, certaines problématiques sont propres à l'Insee ou au SSP et seront plus facilement traités à ce niveau (problèmes d'environnement, de pare-feu par exemple). Par ailleurs, il peut être plus rassurant au début de poser sa question dans un environnement qu'on connaît. 

### Comment poser sa question ?

Pour rendre votre question facile à appréhender, il est la plupart du temps nécessaire d'avoir les éléments suivants :

1. le fichier de données initial ;
2. le code que vous exécutez ;
3. ce que vous obtenez (données, messages d'erreur éventuel) ;
4. ce que vous aimeriez obtenir. 

Bien sûr les étapes deux et trois sont facultatives pour les cas où vous ne savez pas par quel bout prendre le problème, et n'avez donc pas écrit de code. Dans ce cas, donnez vous quand même la peine d'expliquer à quoi vous souhaitez arriver et de quoi vous souhaitez partir. 

**Il est essentiel que l'exemple se suffise à lui-même. N'oubliez pas les appels éventuels de _packages_ et travaillez avec des jeux de données publiques ou que vous reconstruisez dans votre code**. Un bon test peut être de vider l'environnement, de relancer la session et d'exécuter votre exemple pour vérifier qu'il s'exécute correctement.

::: {.conseil}
Il arrive fréquemment que des erreurs soient difficiles à reproduire du fait d'un environnement différent. Il peut être utile, à la fin d'une question, de faire figurer le résultat de la commande `sessionInfo()` pour aider les autres personnes à comprendre dans quel environnement un problème advient
:::
## Comment rédiger sa question ?

Une question doit être lisible et le plus intelligible possible. L'attention
à la mise en forme est de rigueur. La plupart des sites d'entraide ou des
messageries instantanées reposent sur la syntaxe `Markdown` ce qui
permet d'isoler les blocs de code afin de les rendre
lisibles [la fiche `R Markdown` développe avec plus de détails ce format d'édition](#rmarkdown). 

Les morceaux de code doivent être introduits dans des blocs de la manière suivante:

~~~markdown
```r
print("toto")
```
~~~

Ceci permet de séparer de manière claire les éléments
 à exécuter dans `R` d'autres éléments (explications notamment). Le
 package `reprex` propose des fonctionnalités pour faciliter
 l'édition d'un *post* à partir d'un script ([exemple ici](https://thinkr.fr/reprex-ou-comment-demander-de-laide-efficacement/#Un_exemple_d%E2%80%99utilisation_de_%7Breprex%7D))

## Zoom sur stackoverflow {#stack-overflow}

### Fonctionnement général

[Stackoverflow](https://stackoverflow.com) est un site de questions/réponses qui fait référence sur de nombreux sujets en lien avec l'informatique. Son fonctionnement s'apparente à un forum : des utilisateurs posent des questions, d'autres y répondent. Une particularité essentielle est que les réponses ne sont pas ordonnées chronologiquement mais par _pertinence_, par ailleurs, si la question a besoin d'être précisée ou mise à jour, l'auteur est invité à la modifier. L'objectif étant d'obtenir une question, aussi claire que possible, avec juste après la réponse la plus pertinente, et éventuellement les autres réponses ensuite. Cela évite d'avoir, comme sur un forum, à dérouler le raisonnement et les errements éventuels qui ont permis d'obtenir la réponse. Dans le même esprit, le site demande d'éviter les commentaires "parasites" : pas de bonjour ou de merci, on cherche à obtenir quelque chose d'aussi fonctionnel que possible. 

La pertience des réponses est établi en fonction du choix de la personne qui a posé la question (elle décide de la réponse qu'elle _accepte_), et des autres contributeurs : tout le monde peut _voter_ pour les réponses, positivement ou négativement.

Les contributeurs de Stackoverflow sont hierarchisés par un complexe système de réputation : on en gagne quand on pose des questions jugées pertinentes, ou davantage quand on donne des réponses qui sont jugées pertinentes mais on peut également en perdre dans le cas contraire. Plus un contributeur a de réputation, plus il peut contribuer au site (nombre de vote disponible, possibilité d'éditer les questions d'autres contributeurs voir d'en supprimer).

### Poser une question sur Stackoverflow

En plus des conseils donner plus haut, quelques règles spécifiques à Stackoverflow :

* il est nécessaire de créer un compte pour poser une question (mais pas pour consulter les réponses) ;
* accordez une importance particulière au titre de votre question, votre titre doit résumer le problème autant que possible ;
* pensez à insérer des _tags_. Les _tags_ permettent de catégoriser les questions. Ainsi, le _tag_ `#r` rassemble toutes les questions ayant trait à `R`, le _tag_ `#dplyr` celles ayant trait à _dplyr_, ainsi de suite ;
* répondez aux éventuelles questions de clarification qu'on vous posera en commentaires en éditant votre question ;
* votez pour les réponses qui vous semblent pertinentes. Cela aide la communauté, et donc vous également, à déterminer les meilleures solutions à un problème ;
* prenez soin de votre réputation en évitant les doublons et en prenant le temps de rédiger votre question.

## Pour en savoir plus

* [Comment poser une question sur le site de Stackoverflow](https://stackoverflow.com/help/how-to-ask)
* [Comment faire un bon exemple reproductible avec R](https://stackoverflow.com/a/5963610/9197726)
* [Reprex, ou comment demander de l’aide efficacement](https://thinkr.fr/reprex-ou-comment-demander-de-laide-efficacement)
