# Utilisation au quotidien de `Git`

Cette fiche n'a pas vocation à présenter de manière extensive `Git`, langage
qui, par sa richesse, mérite à lui seul un ouvrage dédié. Le lecteur sera
ainsi régulièrement renvoyé vers des éléments plus détaillés, notamment
la formation *Travail collaboratif avec R*.

Cette fiche vise à présenter l'utilisation courante de `Git` pour
un utilisateur de `R` et à formuler quelques conseils et recommandations.
L'exaustivité n'est pas recherchée. 

Le parti pris de présenter en priorité l'interface Rstudio est qu'elle facilite
l'appropriation de la gymnastique Git. L'ensemble des gestes présentés dans 
cette fiche peuvent être effectués sans recourir à une interface graphique. Pour
les utilisateurs intéressés par une telle approche, le nom de l'opération
git en question sera systématiquement donné. Pour un débutant, il est néanmoins
recommandé de privilégier l'interface graphique qui facilite les premiers pas. 
A mesure que l'on devient plus confiant, on tend à utiliser de plus en plus
la ligne de commande jusqu'à ne plus vouloir s'en passer.


## Tâches concernées et recommandations

L'utilisateur souhaite utiliser l'outil `Git` pour contrôler l'évolution
de son projet `R`. Cette fiche suppose que les éléments de configuration
de `Git`, présentés dans la Fiche XXXX, sont fonctionnels. 

::: {.recommandation data-latex=""}

* Utiliser `Git` pour tout projet `R` intégrant des codes, des
* Ne pas utiliser `Git` pour les données
* Pour les tâches courantes, privilégier l'interface Rstudio
:::

## Vocabulaire

forge
clone

## Principe de Git

`Git` est un outil formidable pour gérer l'évolution d'un projet impliquant
du code informatique (`R` ou un autre langage) ou simplement archiver
l'évolution de scripts sur lesquels on peut vouloir revenir dans un futur
plus ou moins lointain ou dont on peut vouloir piocher une partie pour un
autre projet. Si vous n'êtes pas encore convaincu,
une liste plus longue des raisons d'utiliser Git est
[disponible ici](https://linogaliana.gitlab.io/collaboratif/git.html#pourquoi-utiliser-la-gestion-de-version)

Pour résumer, l'objectif de `Git` est de favoriser une collaboration efficace
avec d'autres personnes mais aussi avec votre premier collaborateur, votre
*moi* futur. `Git` permet d’archiver et de retracer les évolutions d’un code
ligne à ligne, et de travailler à plusieurs sur le même code de façon cohérente. 


## Utiliser Git avec `R` dans un projet `Rstudio`

Il est possible de connecter un projet `Rstudio` a tout moment avec `Git`, que
ce soit à la création de celui-ci ou, si cela n'a pas été fait lors de la
création, plus tard

::: {.recommandation data-latex=""}

* Au lancement d'un projet, il est recommandé de créer un dépôt vide sur une
forge (`Gitlab`, `Github`...) et de le cloner pour disposer d'une copie de
travail en local. Ceci est développé dans la Section XXX
* Si un projet n'a pas été initialisé avec `Git`, taper dans la console de
`R` la commande `usethis::use_git`. Ceci est développé dans la Section XXX
* Ajouter, pour avoir la conscience tranquille, quelques lignes au
fichier `.gitignore` afin d'éviter de mettre des fichiers de données
sous contrôle de version : `*.csv`, `.xls`, `sas7bdat`... Ceci est développé dans la Section XXX
:::


### A l'initialisation d'un projet

Lorsqu'on créé un projet `Rstudio` (voir fiche XXXX), 

3 cas de figures:

* clone
* à l'initialisation du projet
* ajouter git à un projet qui n'avait pas de contrôle de version (recommandation: utilise usethis)


Recommandation : clone

## Premiers pas en local 

add commit et regarder l'interface graphique

## Interagir avec le dépôt

## Créer des branches

## Utiliser le terminal

## Pour aller plus loin

* [Formation *Travail collaboratif avec R*](https://linogaliana.gitlab.io/collaboratif/git.html)
* [*Happy Git with R*](https://happygitwithr.com/)