# Demander de l'aide sous `R`

## Tâches concernées et recommandations

Votre code ne fait pas ce que vous voudriez qu'il fasse et vous ne comprenez pas ce qui ne va pas. Il est alors opportun de pouvoir se faire aider. Cette fiche détaille à qui vous pouvez demander de l'aide et comment le faire pour que vous puissiez résoudre votre problème.

::: {.recommandation data-latex=""}
* commencer par isoler le problème en le reproduisant sur un jeu de données publique (_iris_, _cars_,... ) ;
* si vous avez un message d'erreur, copier le dans un moteur de recherche ;
* posez votre question sur stackoverflow, un forum ou un service de messagerie instantanée en incluant le code permettant de reproduire l'erreur.
:::

## Commencer par isoler le problème

Cette étape est essentielle : quand on rencontre un problème en travaillant sur un programme, les sources d'erreurs potentielles sont multiples et pas évidentes à identifier si on s'en tient aux messages d'erreurs. En particulier, le problème peut venir d'un jeu de données mal maîtrisé : présence de valeurs manquantes, valeurs hors normes, problème de format, _group_by_ qui traîne... Il peut également se situer à une étape intermédiaire de votre programme, et pas à l'étape que vous venez de rajouter. 

Vous pouvez donc commencez par remonter votre programme en vérifiant à chaque étape si le résultat intermédiaire correspond à ce que vous attendez, jusqu'à trouver l'instruction qui pose problème. Ceci fait, essayez de reproduire ce que vous souhaitez faire, mais avec un jeu de données publique (_iris_, _cars_, _ggplot2::diamonds_...). L'intérêt de cette opération est double :

* si cela fonctionne, vous savez que le problème provient de votre jeu de données. Il faut donc vérifier à nouveau les étapes précédentes du programme ;
* si cela ne fonctionne pas vous disposez maintenant d'un exemple que vous allez pouvoir utiliser pour poser votre question.

Si vous ne trouvez pas de jeu de données adapté à votre problème, vous pouvez en constituer un nouveau à l'aide de la fonction _tibble_ ou _data.frame_. 

Dans bien des cas, isoler le problème va vous permettre de le résoudre. Si ce n'est pas le cas, il vous faut alors aller chercher de l'aide.

## Chercher de l'aide

### La question a-t'elle déjà été posée ?

La première chose à vérifier est que la question n'a pas déjà été posée : en particulier quand on débute, il est rare de rencontrer un problème dont la solution ne figure pas en ligne. Si vous avez un message d'erreur, vous pouvez le copier/coller dans un moteur de recherche. Si vous n'en avez pas, le plus efficace est d'essayer de formuler votre problème en anglais et de rechercher directement dans un moteur de recherche générique, ou directement sur le moteur de recherche de [Stackoverflow](Zoom sur stackoverflow). 

### Où chercher de l'aide ?

Selon le type de problème, votre niveau en anglais et le temps que vous êtes prêts à attendre, vous pouvez cherche de l'aide aux endroits suivants :

* [Stackoverflow](https://stackoverflow.com/) (SO) est un site de questions/réponses sur de nombreuses thématiques liées à l'informatique. C'est la façon la plus efficace d'obtenir une réponse rapide, y compris sur des sujets particulièrement complexes, pour peu qu'on accete de se plier au formalisme demandé (voir [plus bas](Zoom sur stackoverflow)) ;
* le [groupe slack grrr](https://r-grrr.slack.com) (francophone) dispose d'un canal #questions qui est assez réactif. Toujours en français, le forum du [Cirad](https://fr.wikipedia.org/wiki/Centre_de_coop%C3%A9ration_internationale_en_recherche_agronomique_pour_le_d%C3%A9veloppement) héberge une importante communauté `R`. S'il n'est plus la référence qu'il a été, il est toujours actif ;
* En interne SSP, il est possible de trouver de l'aide sur la messagerie instantanée [Tchap](https://tchap.gouv.fr/), sur le canal _#langage R_ ;
* Enfin, en interne Insee, il y a également un canal dédié sur Tchap (_Insee - Outils stats v2_) ainsi que d'autres sur [rocket-chat](https://rocket-chat.stable.innovation.insee.eu) ([#r](https://rocket-chat.stable.innovation.insee.eu/channel/r), [#r-shiny](https://rocket-chat.stable.innovation.insee.eu/channel/r-shiny),[#rmarkdown](https://rocket-chat.stable.innovation.insee.eu/channel/rmarkdown))

Ces différentes plate-forme sont classées en fonction de leur nombre d'utilisateurs, ce qui a un impact mécanique sur la rapidité des réponses et la chance de tomber sur un utilisateur maîtrisant parfaitement le domaine sur lequel vous cherchez Cependant, certaines problématiques sont propres à l'Insee ou au SSP et seront plus facilement traités à ce niveau (problèmes d'environnement, de pare-feu par exemple). Par ailleurs, il peut être plus rassurant au début de poser sa question dans un environnement qu'on connaît. 

### Comment poser sa question ?

Pour rendre votre question facile à appréhender, il est nécessaire d'avoir les éléments suivants :

* le fichier de donnée initial ;
* le code que vous exécutez ;
* ce que vous obtenez (données, messages d'erreur éventuel) ;
* ce que vous aimeriez obtenir. 

Bien sûr les étapes deux et trois sont facultatives pour les cas où vous ne savez pas par quel bout prendre le problème, et n'avez donc pas écrit de code. 

**Il est essentiel que l'exemple que vous donnez puisse être reproduit intégralement. N'oubliez pas les appels éventuels de _package_ et travaillez avec des jeux de données publiques ou que vous reconstruisez dans votre code**.

## Zoom sur stackoverflow

