# Une étude reproductible avec `targets`

`targets` est une librairie qui fournit des outils d'automatisation d'une chaîne de traitement en R.

## Pourquoi utiliser `targets`?

La librairie `targets` peut être particulièrement intéressante dans le cas d'un projet d'étude qui vise à une forte reproductibilité. Plus précisément, utiliser `targets` pour un projet permet de:

1. Viser la reproductibilité de l'ensemble des étapes de traitement, tout en minimisant au strict nécessaire la répétition de ces étapes, parfois longues
2. Adopter des bonnes pratiques de développement en R par l'usage (modulariser son code, assurer la lisibilité des étapes successives du traitement..)

## Quelles sont les tâches automatisées par `targets`?

Target permets de définir et d'exécuter une chaîne de traitement avec:

* Sauvegarde automatique de résultats intermédiaires, ce qu'on appelle les "targets"
* Traçabilité de ces résultats intermédiaires par `targets`: lors de la répétition d'une exécution de la chaîne de traitement, ils ne sont mobilisés que si ils sont reproductibles.
* Si une fonction ou un input nécessaire au calcul d'une "target" est modifié, `targets` repère automatiquement les étapes à reconduire, et seulement celles-ci

Ainsi, le lancement du traitement et la vérification de la reproductibilité sont effectués ensemble au cours du développement du projet par l'appel de `tar_make()`. Vérifier la reproductibilité ne revient pas à 'tout relancer' de 0 (ce qui représente un coût élevé). `targets` automatise le travail d'aller-retour dans les étapes d'une étude (j'ai modifié l'étape 1, il faut donc que je relance l'étape 2 qui en dépend...), en construisant un graphe des dépendances des différentes étapes du traitement.  



Pour la suite de la fiche, prenons l'exemple d'une étude qui se structurerait suivant les étapes suivantes: 0 Charger les données, 1. Traiter les données, 2. Produire des résultats, 3. Représenter les résultats. 

## Un projet minimal pour comprendre l'essentiel

Les principaux éléments:

* `_targets.R` pour décrire les éléments de configuration (e.g. packages utilisés) et l'enchaînement des traitements. 
* Un dossier `R` comprenant les scripts définissant les fonctions utilisées par le projet
* Un dossier `data` pour les données externes (non générées au cours du projet)

TODO: 
1. Reprendre les éléments de https://books.ropensci.org/targets/walkthrough.html sur un exemple maison (sans données externes d'abord).

2. Run/Modification minimale/ Rerun

3. Améliorer la lisibilité de ce premier script en utilisant des fonctions.

## Le projet `targets` et l'extérieur

Où s'arrête le suivi de modifications? Comment suivre également les modifications des fichiers d'entrée (non généré par le projet)?

* Les données/fichiers externes (`format = 'file'`)
* Les packages / (renv?) 

## Dynamic Branching

- Appliquer une même fonction à des variantes d'arguments (par exemple, un graphique de restitution pour plusieurs populations d'intérêt), et créer autant de targets automatiquement (sans écrire explicitement dans `_targets.R` chacune d'entre elles)

`map`, `cross`

## Debug

`tar_option_set(debug = "matarget")` 

## tarchetypes pour construire des pipelines plus complexes


### Rmarkdown

Construire un markdown au cours de la pipeline.
`tar_render`, `tarchetypes` ?

### Static Branching

- Définir des méta-tâches: static branching, `tar_combine`

## Source

Landau, W. M., (2021). The targets R package: a dynamic Make-like function-oriented pipeline toolkit for reproducibility and high-performance computing. Journal of Open Source Software, 6(57), 2959, https://doi.org/10.21105/joss.02959 

## Pour en savoir plus

* Manuel d'utilisation de `targets` https://books.ropensci.org/targets/ 
* High Performance Computing avec `targets`: https://books.ropensci.org/targets/hpc.html 
* https://cran.r-project.org/web/packages/targets/targets.pdf 
* https://docs.ropensci.org/tarchetypes/ 
* Un exemple https://github.com/InseeFrLab/lockdown-maps-R/ 
