on: [pull_request]

name: test compilation PDF

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    container: inseefrlab/utilitr:latest
    steps:
      - name: Checkout Repository
        if: ${{ github.repository == 'inseefrlab/utilitr' }}
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        uses: actions/checkout@master
      - name: Checkout Repository
        if: ${{ github.repository != 'inseefrlab/utilitr' }}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/checkout@master
      - name: Install Dependencies
        if: ${{ github.repository == 'inseefrlab/utilitr' }}
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          Rscript -e "install.packages(c('remotes'))"
          Rscript -e "remotes::install_github('rstudio/rmarkdown')"
          Rscript -e "remotes::install_github('rstudio/pagedown')"
          Rscript -e "remotes::install_github('rstudio/htmltools')"
      - name: Install Dependencies
        if: ${{ github.repository != 'inseefrlab/utilitr' }}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e "install.packages(c('remotes'))"
          Rscript -e "remotes::install_github('rstudio/rmarkdown')"
          Rscript -e "remotes::install_github('rstudio/pagedown')"
          Rscript -e "remotes::install_github('rstudio/htmltools')"
      - name: Render Book
        run: |
          mkdir _pagedown_output -p
          Rscript -e "utilitr::pdf_document()"
      - uses: actions/upload-artifact@v2
        with:
          name: DocumentationR_pagedown
          path: _pagedown_output/DocumentationR.pdf
          retention-days: 5
